apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: websites.devops.com

spec:
  group: devops.com
  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                domain:
                  type: string
                replicas:
                  type: integer
                image:
                  type: string
  scope: Namespaced
  names:
    plural: websites
    singular: website
    kind: Website
    shortNames:
     - ws    
