kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: nginx-backend-namespace
spec:
  selector:
    app: backend
  ports:
   - protocol: TCP
     port: 3003
     targetPort: 3003
