apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
  namespace: nginx
spec:
  schedule: "*/1 * * * *"  # For every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            command:
              - sh
              - -c
              - tar -czf /tmp/backup-$(date +%F-%H%M%S).tar.gz /data
            volumeMounts:
              - name: datavol
                mountPath: /data
          restartPolicy: Never
          volumes:
            - name: datavol
              hostPath:
                path: /home/naveed/data  
                type: Directory

