apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello Kubernetes Job"]
      restartPolicy: Never

